// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.bz.model;

public final class Test {
	private Test() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface TestModelOrBuilder extends
	// @@protoc_insertion_point(interface_extends:com.bz.proto.TestModel)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>required int32 id = 1;</code>
		 *
		 * <pre>
		 * required string aa = 1;
		 * </pre>
		 */
		boolean hasId();

		/**
		 * <code>required int32 id = 1;</code>
		 *
		 * <pre>
		 * required string aa = 1;
		 * </pre>
		 */
		int getId();

		/**
		 * <code>optional string bb = 3;</code>
		 */
		boolean hasBb();

		/**
		 * <code>optional string bb = 3;</code>
		 */
		java.lang.String getBb();

		/**
		 * <code>optional string bb = 3;</code>
		 */
		com.google.protobuf.ByteString getBbBytes();
	}

	/**
	 * Protobuf type {@code com.bz.proto.TestModel}
	 */
	public static final class TestModel extends
			com.google.protobuf.GeneratedMessage implements
	// @@protoc_insertion_point(message_implements:com.bz.proto.TestModel)
			TestModelOrBuilder {
		// Use TestModel.newBuilder() to construct.
		private TestModel(
				com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private TestModel(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet
					.getDefaultInstance();
		}

		private static final TestModel defaultInstance;

		public static TestModel getDefaultInstance() {
			return defaultInstance;
		}

		public TestModel getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private TestModel(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						id_ = input.readInt32();
						break;
					}
					case 26: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000002;
						bb_ = bs;
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.bz.model.Test.internal_static_com_bz_proto_TestModel_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.bz.model.Test.internal_static_com_bz_proto_TestModel_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							com.bz.model.Test.TestModel.class,
							com.bz.model.Test.TestModel.Builder.class);
		}

		public static com.google.protobuf.Parser<TestModel> PARSER = new com.google.protobuf.AbstractParser<TestModel>() {
			public TestModel parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new TestModel(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<TestModel> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		public static final int ID_FIELD_NUMBER = 1;
		private int id_;

		/**
		 * <code>required int32 id = 1;</code>
		 *
		 * <pre>
		 * required string aa = 1;
		 * </pre>
		 */
		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required int32 id = 1;</code>
		 *
		 * <pre>
		 * required string aa = 1;
		 * </pre>
		 */
		public int getId() {
			return id_;
		}

		public static final int BB_FIELD_NUMBER = 3;
		private java.lang.Object bb_;

		/**
		 * <code>optional string bb = 3;</code>
		 */
		public boolean hasBb() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>optional string bb = 3;</code>
		 */
		public java.lang.String getBb() {
			java.lang.Object ref = bb_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					bb_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string bb = 3;</code>
		 */
		public com.google.protobuf.ByteString getBbBytes() {
			java.lang.Object ref = bb_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				bb_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			id_ = 0;
			bb_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(3, getBbBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						3, getBbBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.bz.model.Test.TestModel parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.bz.model.Test.TestModel parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.bz.model.Test.TestModel parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.bz.model.Test.TestModel parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.bz.model.Test.TestModel parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.bz.model.Test.TestModel parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.bz.model.Test.TestModel parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.bz.model.Test.TestModel parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.bz.model.Test.TestModel parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.bz.model.Test.TestModel parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(com.bz.model.Test.TestModel prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code com.bz.proto.TestModel}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
		// @@protoc_insertion_point(builder_implements:com.bz.proto.TestModel)
				com.bz.model.Test.TestModelOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.bz.model.Test.internal_static_com_bz_proto_TestModel_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.bz.model.Test.internal_static_com_bz_proto_TestModel_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								com.bz.model.Test.TestModel.class,
								com.bz.model.Test.TestModel.Builder.class);
			}

			// Construct using com.bz.model.Test.TestModel.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				id_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				bb_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.bz.model.Test.internal_static_com_bz_proto_TestModel_descriptor;
			}

			public com.bz.model.Test.TestModel getDefaultInstanceForType() {
				return com.bz.model.Test.TestModel.getDefaultInstance();
			}

			public com.bz.model.Test.TestModel build() {
				com.bz.model.Test.TestModel result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.bz.model.Test.TestModel buildPartial() {
				com.bz.model.Test.TestModel result = new com.bz.model.Test.TestModel(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.bb_ = bb_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.bz.model.Test.TestModel) {
					return mergeFrom((com.bz.model.Test.TestModel) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.bz.model.Test.TestModel other) {
				if (other == com.bz.model.Test.TestModel.getDefaultInstance())
					return this;
				if (other.hasId()) {
					setId(other.getId());
				}
				if (other.hasBb()) {
					bitField0_ |= 0x00000002;
					bb_ = other.bb_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.bz.model.Test.TestModel parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.bz.model.Test.TestModel) e
							.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private int id_;

			/**
			 * <code>required int32 id = 1;</code>
			 *
			 * <pre>
			 * required string aa = 1;
			 * </pre>
			 */
			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required int32 id = 1;</code>
			 *
			 * <pre>
			 * required string aa = 1;
			 * </pre>
			 */
			public int getId() {
				return id_;
			}

			/**
			 * <code>required int32 id = 1;</code>
			 *
			 * <pre>
			 * required string aa = 1;
			 * </pre>
			 */
			public Builder setId(int value) {
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 id = 1;</code>
			 *
			 * <pre>
			 * required string aa = 1;
			 * </pre>
			 */
			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object bb_ = "";

			/**
			 * <code>optional string bb = 3;</code>
			 */
			public boolean hasBb() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional string bb = 3;</code>
			 */
			public java.lang.String getBb() {
				java.lang.Object ref = bb_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						bb_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string bb = 3;</code>
			 */
			public com.google.protobuf.ByteString getBbBytes() {
				java.lang.Object ref = bb_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					bb_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string bb = 3;</code>
			 */
			public Builder setBb(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				bb_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string bb = 3;</code>
			 */
			public Builder clearBb() {
				bitField0_ = (bitField0_ & ~0x00000002);
				bb_ = getDefaultInstance().getBb();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string bb = 3;</code>
			 */
			public Builder setBbBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				bb_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:com.bz.proto.TestModel)
		}

		static {
			defaultInstance = new TestModel(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:com.bz.proto.TestModel)
	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_bz_proto_TestModel_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_bz_proto_TestModel_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\nTest.proto\022\014com.bz.proto\"#\n\tTestModel\022"
				+ "\n\n\002id\030\001 \002(\005\022\n\n\002bb\030\003 \001(\tB\024\n\014com.bz.modelB"
				+ "\004Test" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
		internal_static_com_bz_proto_TestModel_descriptor = getDescriptor()
				.getMessageTypes().get(0);
		internal_static_com_bz_proto_TestModel_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_com_bz_proto_TestModel_descriptor,
				new java.lang.String[] { "Id", "Bb", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
